server:
  port: 8080

#logging.level.org.springframework.web=trace
logging:
  level:
    org.springframework.web.reactive.result.method.annotation.RequestMappingHandlerMapping: trace
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: trace

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.18.200.5:3306/test?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: passw0rd

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: cn.netkiller.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn