server:
  port: 8080

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.web.servlet.DispatcherServlet: DEBUG
    org.springframework.web.reactive.result.method.annotation.RequestMappingHandlerMapping: trace
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: trace
  pattern:
    level: '%clr(%5p) %clr([%X{traceId:-},%X{spanId:-},%X{parentId:-}]){green}'
#    level: '%d{ABSOLUTE} [%X{traceId}/%X{spanId}] %-5p [%t] %C{2} - %m%n'
spring:
  application:
    name: engineering
  sleuth:
    enabled: true
    default-logging-pattern-enabled: true
    sampler:
      probability: 1.0
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://172.18.200.5:3306/test?useUnicode=true&characterEncoding=UTF-8
    url: jdbc:mysql://172.18.200.102:3306/test?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&rewriteBatchedStatements=true
    username: root
    password: yijiayou
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
#      ddl-auto: update
  cloud:
    compatibility-verifier:
      enabled: false

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: cn.netkiller.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn